version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/app
    overwrite: yes

permissions:
  - object: /home/ubuntu/app/scripts
    pattern: '**'
    owner: ubuntu
    group: ubuntu
    mode: 777

hooks:
  AfterInstall:
    - location: scripts/start.sh
      timeout: 60
      runas: ubuntu
