version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/app
    overwrite: yes
  - source: ./start.sh
    destination: /home/ubuntu/app/scripts

permissions:
  - object: /
    pattern: '**'
    owner: ubuntu
    group: ubuntu
  - - object: /home/ubuntu/app/scripts
    pattern: "**"
    owner: adm
    group: wheel
    mode: 777
    type:
      - file

hooks:
  AfterInstall:
    - location: scripts/start.sh
      timeout: 60
      runas: ubuntu
