version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/app
    overwrite: yes
  - source: ./start.sh
    destination: /home/ubuntu/app/scripts/start.sh

permissions:
  - object: /
    pattern: '**'
    owner: ubuntu
    group: ubuntu
  - object: /home/ubuntu/app/scripts/start.sh
    owner: ubuntu
    mode: '777'

hooks:
  AfterInstall:
    - location: scripts/start.sh
      timeout: 60
      runas: ubuntu
